<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productosfinancieros [
<!ELEMENT productosfinancieros (producto+)>
<!ELEMENT producto (bono | futuro | acciones)>
<!ELEMENT bono (valoractual?, beneficio)>
<!ELEMENT futuro (elemento, beneficio)>
<!ELEMENT acciones (empresa, beneficio)>
<!ELEMENT valoractual (#PCDATA)>
<!ATTLIST valoractual moneda (dolares | euros | yenes) #REQUIRED>
<!ELEMENT elemento (#PCDATA)>
<!ATTLIST elemento idioma CDATA #REQUIRED>
<!ELEMENT empresa (#PCDATA)>
<!ATTLIST empresa pais (usa | alemania | japon | españa) #REQUIRED>
<!ELEMENT beneficio (#PCDATA)>
]>

<productosfinancieros>
  <producto>
    <bono>
      <valoractual moneda="yenes">2.212</valoractual>
      <beneficio>-2.83</beneficio>
    </bono>
  </producto>
  <producto>
    <futuro>
      <elemento idioma="español">`Petroleo</elemento>
      <beneficio>-3.83</beneficio>
    </futuro>
  </producto>
  <producto>
    <acciones>
      <empresa pais="usa">ENRON</empresa>
      <beneficio>2.91</beneficio>
    </acciones>
  </producto>
</productosfinancieros>