=== Cristian5545/proba1/Carpeta con todo/Lenguaj de marcas/xsdalumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="bdalumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element  name="alumno" maxOccurs="unbounded">
      <xs:complexType>
    <xs:sequence>
          <xs:element name="nombre" type="xs:string" />
          <xs:element name="padre" type="xs:string" />
          <xs:element name="madre" type="xs:string" />
          <xs:element name="edad" type="xs:int" />
          <xs:element name="ciudad" type="xs:string" />
  </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== Cristian5545/proba1/Carpeta con todo/Lenguaj de marcas/Esquemas XML.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<bdalumnos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="xsdalumnos.xsd">
<alumno>
    <nombre>José Antonio</nombre>
    <padre>José Luis</padre>
    <madre>Carmen</madre>
    <edad>Málaga</edad>
</alumno>
<alumno>
      <nombre>Francisco Jesús</nombre>
      <padre>José</padre>
      <madre>María</madre>
      <edad>25</edad>
      <ciudad>Barcelona</ciudad>
</alumno>
</bdalumnos>
